name: "자바 및 JVM"
description: "면접에서 나올 수 있는 자바 및 JVM 관련 대표 질문을 선정한다"
title: "[자바 및 JVM]: "
labels: "자바 및 JVM"
body:
  - type: textarea
    attributes:
      label: 📝 키워드 선정
      description: 키워드 선정 이유에 대해 알려주세요!
      placeholder: 참고 자료 혹은 관련 URL이 있다면 추가해주세요!
    validations:
      required: true
 